kumuluzee:
  name: dostavca-auth
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://35.195.253.165:8080
    http:
      port: 8080
  discovery:
    cluster: dostavca
    etcd:
      hosts: http://35.195.125.144:2379
    ttl: 20
    ping-interval: 15