kumuluzee:
  name: dostavca-auth
  env:
      name: dev
  version: 1.0.0
  server:
    http:
      port: 8080
  discovery:
    etcd:
      hosts: http://localhost:2379
    ttl: 20
    ping-interval: 15